src/openfinances/urls.py
from django.contrib import admin
from django.urls import path

from app.views import BordereauLivraisonCreateView, BordereauLivraisonView, ClientCreateView, ClientUpdateView, ClientView, DashView, FactureCreateView, FactureUpdateView, FactureView, ReportCreateView, ReportUpdateView, ReportView, index, signup


urlpatterns = [
    
    path('', index, name="index"),

    path('signup', signup, name="signup"),

    path('dashbord', DashView.as_view(), name="dash-view"),
    
    path('bls/', BordereauLivraisonView.as_view(), name="bl-list"),
    path('bl/<int:pk>', BordereauLivraisonView.as_view(), name="view-list"),
    path('bl/create', BordereauLivraisonCreateView.as_view(), name="bl-create"),
    path('bl/facture/<int:pk>/create', BordereauLivraisonCreateView.as_view(), name="bl-facture-create"),
    
    path('clients/', ClientView.as_view(), name="client-list"),
    path('client/<int:pk>', ClientView.as_view(), name="view-list"),
    path('client/create', ClientCreateView.as_view(), name="client-create"),
    path('client/<int:pk>/update', ClientUpdateView.as_view(), name="client-update"),
    
    path('factures/', FactureView.as_view(), name="facture-list"),
    path('facture/<int:pk>', FactureView.as_view(), name="view-list"),
    path('facture/create', FactureCreateView.as_view(), name="facture-create"),
    path('facture/<int:pk>/update', FactureUpdateView.as_view(), name="facture-update"),
    
    path('reports/', ReportView.as_view(), name="report-list"),
    path('report/facture/<int:pk>/create', ReportCreateView.as_view(), name="report-facture-create"),
    path('report/<int:pk>/update', ReportUpdateView.as_view(), name="report-update"),


    path('admin/', admin.site.urls),
]

src/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Client(models.Model):
    denomination = models.CharField(max_length=100, verbose_name="Dénomination",)
    signe = models.CharField(max_length=100, verbose_name="Signe",)
    numero_enreg = models.CharField(max_length=100, verbose_name="Numéro d'enregistrement",)
    creator = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Créateur",)
    date_creation = models.DateTimeField(auto_now_add=True, editable=False, verbose_name="Date de création",)
    date_update = models.DateTimeField(auto_now=True, editable=False, verbose_name="Date de modification",)

    class Meta:
        verbose_name = "Client"
        verbose_name_plural = "Clients"

    def __str__(self):
        return self.denomination


class Facture(models.Model):
    numero_ordre = models.CharField(max_length=100, verbose_name="Numéro d'ordre",)
    date_facture = models.DateField(verbose_name="Date de la facture",)
    montant_total = models.IntegerField(verbose_name="Montant total",)
    client = models.ForeignKey(Client, on_delete=models.PROTECT, verbose_name="Client",)
    creator = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Créateur",)
    date_creation = models.DateTimeField(auto_now_add=True, editable=False, verbose_name="Date de création",)
    date_update = models.DateTimeField(auto_now=True, editable=False, verbose_name="Date de modification",)

    class Meta:
        verbose_name = "Facture"
        verbose_name_plural = "Factures"

    def __str__(self):
        return self.numero_ordre
    
    @property
    def nombre_bouteilles(self):
        return Rapport.objects.get(facture = self).nombre_bouteilles

    @property
    def poids_bouteilles(self):
        return Rapport.objects.get(facture = self).poids_bouteilles

    @property
    def total_par_categories(self):
        return Rapport.objects.get(facture = self).total_par_categories

class Rapport(models.Model):
    nombre_bouteilles = models.IntegerField(default=0, verbose_name="Nombre de bouteilles",)
    poids_bouteilles = models.IntegerField(default=0, verbose_name="Poids de bouteilles",)
    total_par_categories = models.IntegerField(default=0, verbose_name="Total par catégories",)
    facture = models.ForeignKey(Facture, on_delete=models.CASCADE, verbose_name="Facture",)
    date_creation = models.DateTimeField(auto_now_add=True, editable=False, verbose_name="Date de création",)
    date_update = models.DateTimeField(auto_now=True, editable=False, verbose_name="Date de modification",)

    class Meta:
        verbose_name = "Rapport"
        verbose_name_plural = "Rapports"

    def __str__(self):
        return self.facture.numero_ordre


class BordereauLivraison(models.Model):
    date_livraison = models.DateField(verbose_name="Date de livraison",)
    numero_bl = models.CharField(max_length=100, verbose_name="Numéro du bordereau",)
    facture = models.ForeignKey(Facture, on_delete=models.CASCADE, verbose_name="Facture",)
    creator = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Créateur",)
    date_creation = models.DateTimeField(auto_now_add=True, editable=False, verbose_name="Date de création",)
    date_update = models.DateTimeField(auto_now=True, editable=False, verbose_name="Date de modification",)

    class Meta:
        verbose_name = "Bordereau de livraison"
        verbose_name_plural = "Bordereaux de livraison"

    def __str__(self):
        return self.numero_bl

src/app/templates/pages/bl.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Bordereaux de Livraison | Open finances</title>{% endblock %}


{% block content %}

    <!-- borderaux de livraison -->
    <section id="BDL" class="active">
        <h2 class="text-xl sm:text-2xl font-medium text-black/80">Bordereaux de Livraison</h2>
        <div style="text-align: right; margin: 40px 0px;">
            <a href="{% url 'bl-create' %}"
                style="
                    background-color: rgb(29 78 216); 
                    color: white; 
                    border-radius: 0.375rem; 
                    margin-top: 1rem;" 
                class="rounded-md w-48 p-2 mx-2">
                    Nouveau BL
            </a>
        </div>
        <!-- slider -->
        <!-- <div class="slider flex gap-4 w-fit h-fit my-3 sm:my-7 "> -->
        <div class="slider flex flex-wrap justify-center sm:justify-normal  gap-8 sm:gap-4 w-full h-fit my-3 sm:my-7">
            {% for bl in page_obj %}

                <article>
                    <div class="flex flex-col gap-4 h-56 overflow-hidden  ">
                        <h2 class=" flex justify-between text-base font-semibold  text-black">
                            <span>{{ bl.numero_bl }}</span>
                            <span>{{ bl.date_livraison }}</span>
                        </h2>
                        <p><span>Client : </span> {{ bl.facture.client.denomination|default:'Aucun'|title }}</p>
                        <p><span>Type de bouteille : </span> {{ bl.facture.rapport_set.first.poids_bouteilles|default:'Inconu' }}</p>
                        <p><span>Quantité : </span> {{ bl.facture.rapport_set.first.nombre_bouteilles|default:'Inconue' }}</p>
                        <p><span>Total reçu : </span> {{ bl.facture.montant_total }}</p>
                    </div>
                    <button class="text-blue-700 font-medium">Modifier</button>
                </article>
                
            {% endfor %}
            
            
            <!-- <article>
                <div class="flex flex-col gap-4 h-56 overflow-hidden  ">
                    <h2 class=" flex justify-between text-base font-semibold  text-black">
                        <span>BL n°000123</span>
                        <span>18/01/2024</span>
                    </h2>
                    <p><span>Client : </span> Bantou Samba</p>
                    <p><span>Type de bouteille : </span> Poids 12</p>
                    <p><span>Quantité : </span> 2</p>
                    <p><span>Total reçu : </span> 12.800 FCFA</p>
                    <p><span>Notes additionnelles : </span> RAS</p>
                </div>
                <span class="m-auto text-blue-700 text-xl">...</span>
                <button class="text-blue-700 font-medium">Modifier</button>
            </article> -->
        </div>
        
        <!-- <div class=" indicator">
            <button>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" class="w-5 sm:w-8">
                    <path d="M560-240 320-480l240-240 56 56-184 184 184 184-56 56Z" />
                </svg>
            </button>
            <ul class=" ">
                <li>1</li>
                <li class="active">2</li>
                <li>3</li>
            </ul>
            <button>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" class="w-5 sm:w-8 rotate-180">
                    <path d="M560-240 320-480l240-240 56 56-184 184 184 184-56 56Z" />
                </svg>
            </button>
        </div> -->

        
        {% include "components/pagination.html" with page_obj=page_obj %}

    </section>

{% endblock %}

src/app/templates/pages/client.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Clients | Open finances</title>{% endblock %}


{% block content %}

    <!-- client -->
    <section id="CLIENT" class="active">
        <h2 class="mb-8 lg:mb-0 text-xl sm:text-2xl font-medium text-black/80">Clients</h2>
        <div style="text-align: right; margin: 40px 0px;">
            <a href="{% url 'client-create' %}"
                style="
                    background-color: rgb(29 78 216); 
                    color: white; 
                    border-radius: 0.375rem; 
                    margin-top: 1rem;" 
                class="rounded-md w-48 p-2 mx-2">
                    Nouveau client
            </a>
        </div>
        <div
            class="slider flex flex-wrap justify-center sm:justify-normal  gap-8 sm:gap-4 w-full h-fit my-3 sm:my-7 ">
                
                {% for cl in page_obj %}
                    <article>
                        <div class="flex flex-col gap-4 h-48 overflow-hidden  ">
                            <h2 class=" flex justify-between text-base font-semibold  text-black">Client n° {{ cl.numero_enreg }}</h2>
                            <p><span>Dénomination : </span> {{ cl.denomination }}</p>
                            <p><span>Signe distinctif : </span> {{ cl.signe }}</p>
                            <p><span>Numéro d'enregistrement (cc) : </span> {{ cl.numero_enreg }}</p>
                        </div>
                        <a href="{% url 'client-update' pk=cl.pk %}" class="text-blue-700 font-medium text-center">Modifier</a>
                    </article>
                {% endfor %}
            
            <!-- <article>
                <div class="flex flex-col gap-4 h-48 overflow-hidden  ">
                    <h2 class=" flex justify-between text-base font-semibold  text-black">Client n°000123</h2>
                    <p><span>Nom(s) : </span> Bantou Samba</p>
                    <p><span>Dénomination : </span> </p>
                    <p><span>Signe distinctif : </span> </p>
                    <p><span>Numéro d'enregistrement (cc) : </span> </p>
                </div>
                <button class="text-blue-700 font-medium">Lire tout</button>
            </article> -->

        </div>

        {% include "components/pagination.html" with page_obj=page_obj %}
    </section>

{% endblock %}

src/app/templates/pages/facture.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Factures | Open finances</title>{% endblock %}


{% block content %}

    <!-- Facture -->
    <section id="FACTURE" class="active">
        <h2 class="mb-8 lg:mb-0 text-xl sm:text-2xl font-medium text-black/80">Factures</h2>
        <div style="text-align: right; margin: 40px 0px;">
            <a href="{% url 'facture-create' %}"
                style="
                    background-color: rgb(29 78 216); 
                    color: white; 
                    border-radius: 0.375rem; 
                    margin-top: 1rem;" 
                class="rounded-md w-48 p-2 mx-2">
                    Nouvelle facture
            </a>
        </div>
        <div
            class="slider flex flex-wrap justify-center sm:justify-normal  gap-8 sm:gap-4 w-full h-fit my-3 sm:my-7 ">
            
            {% for fa in page_obj %}
                <article>
                    <div class="flex flex-col gap-4 h-58 mb-4 overflow-hidden  ">
                        <h2 class=" flex justify-between text-base font-semibold  text-black">
                            <span>{{ fa.numero_ordre }}</span>
                            <span>{{ fa.date_facture }}</span>
                        </h2>
                        <p><span>Nom de l'article : </span> Bouteilles de gaz</p>
                        <p><span>Quantité de bouteilles : </span> {{ fa.rapport_set.first.poids_bouteilles|default:'Inconu' }}</p>
                        <p><span>Prix Total : </span> {{ fa.montant_total }}</p>
                        <hr />
                        <p><span>Total de bouteilles: </span> {{ fa.rapport_set.first.nombre_bouteilles }}</p>
                        <p><span>Poids total: </span> {{ fa.rapport_set.first.poids_bouteilles }}</p>
                        <p><span>Total par catégorie: </span> {{ fa.rapport_set.first.total_par_categories }}</p>
                    </div>
                    
                    <hr />
                    
                    {% if fa.bordereaulivraison_set.first %}
                        <a href="{% url 'view-list' pk=fa.bordereaulivraison_set.first.pk %}" class="m-auto text-blue-700 text-xl text-center">Voir le bordereau de livraison</a>
                    {% else %}
                        <a href="{% url 'bl-facture-create' pk=fa.pk %}" class="m-auto text-xl text-center" style="color: rgb(34 197 94);">Ajouter un bordereau de livraison</a>
                    {% endif %}

                    <a href="{% url 'facture-update' pk=fa.pk %}" class="text-blue-700 font-medium text-center">Modifier</a>
                </article>
            {% endfor %}
            
            <!-- <article>
                <div class="flex flex-col gap-4 h-58 mb-4 overflow-hidden  ">
                    <h2 class=" flex justify-between text-base font-semibold  text-black">
                        <span>BL n°000123</span>
                        <span>18/01/2024</span>
                    </h2>
                    <p><span>Nom de l'article : </span> </p>
                    <p><span>Quantité de bouteilles : </span> </p>
                    <p><span>Poids unitaire : </span> </p>
                    <p><span>Prix unitaire: </span> </p>
                    <p><span>Total par catégorie: </span> </p>
                    <p><span>Total : </span> </p>
                </div>
                <button class="text-blue-700 font-medium">Voir le bordereau de livraison</button>
            </article> -->

        </div>

        {% include "components/pagination.html" with page_obj=page_obj %}
    </section>

{% endblock %}

src/app/templates/pages/form.html
{% extends 'base.html' %}
{% load static %}

{% load add_attr %}

{% block title %}<title>Formulaire {{ title }} | Open finances</title>{% endblock %}

{% block content %}

    <section id="BDL">
        <h2 class="text-xl sm:text-2xl my-4 font-medium text-black/80">{{ title }}</h2>
        
        <form method="POST" class="flex flex-col my-3 sm:my-5 flex gap-2">
            {% csrf_token %}

            {% for field in form %}
                
                <div class="py-2">
                    {{ field.errors }}
                </div>

                <b class="px-2">{{ field.label }}:</b>
                <label for="" class="w-1/2" style="text-align: left;">
                    {{ field|add_attr:"style=text-align: left;" }}
                </label>

                {% if field.help_text %}
                    <p class="help" id="{{ field.auto_id }}_helptext">
                        {{ field.help_text|safe }}
                    </p>
                {% endif %}
                
            {% endfor %}

            <div>
                <button type="submit" 
                    style="
                        background-color: rgb(29 78 216); 
                        color: white; 
                        border-radius: 0.375rem; 
                        margin-top: 1rem;" 
                    class="rounded-md w-48 p-2 mx-2">Enregistrer
                </button>
            </div>

        </form>
        
    </section>

{% endblock %}

src/app/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Dash Board | Open finances</title>{% endblock %}

{% block content %}

    <section id="HOME" class="active">

        <h2 class="text-xl sm:text-2xl  text-black/80">Bonjour, <span class="font-medium text-yellow">{% if user.is_authenticated %} {{ user.username|title }} {% endif %}
            </span>!</h2>
        <p class="text-sm py-2">Voici l'ensemble de vos opérations !</p>
        <div class=" flex gap-4 my-5 w-fit ">
            <div
                class="flex flex-col gap-3 p-5 rounded-[25px] border-[1px] border-gray-950 w-[20.93rem] sm:w-[60vw] md:w-[40vw] lg:w-[26vw]">
                <h2 class="font-medium text-black/80">Total Utilisateurs</h2>
                <span class="text-4xl font-semibold">{{ nb_users }}</span>
                <!-- <p class="flex gap-2">
                    <img src="{% static 'img/graph2.png' %}" class="w-5 h-5" alt="">
                    <span class="text-green-500">+15%</span>
                    depuis le mois précédent
                </p> -->
            </div>
            <div
                class="flex flex-col gap-3 p-5 rounded-[25px] border-[1px] border-gray-950 w-[20.93rem]  sm:w-[60vw] md:w-[40vw] lg:w-[26vw]">
                <h2 class="font-medium text-black/80">Total Clients</h2>
                <span class="text-4xl font-semibold">{{ nb_clients }}</span>
                <!-- <p class="flex gap-2 w-fit">
                    <img src="{% static 'img/graph2.png' %}" class="w-5 h-5" alt="">
                    <span class="text-green-500">+15%</span>
                    depuis le mois précédent
                </p> -->
            </div>
            <div
                class="flex flex-col gap-3 p-5 rounded-[25px] border-[1px] border-gray-950 w-[20.93rem]  sm:w-[60vw] md:w-[40vw] lg:w-[26vw]">
                <h2 class="font-medium text-black/80">Total Factures</h2>
                <span class="text-4xl font-semibold">{{ nb_factures }}</span>
                <p class="flex gap-2">
                    {% if comp_last_mouth_factures >= 0 %}
                        <img src="{% static 'img/graph2.png' %}" class="w-5 h-5" alt="">
                        <span class="text-green-500">
                            +{{ comp_last_mouth_factures }}%
                        </span>
                    {% else %} 
                        <img src="{% static 'img/graph2.png' %}" class="w-5 h-5" alt="">
                        <span style="color: red;">
                            -{{ comp_last_mouth_factures }}%
                        </span>
                    {% endif %} 
                    
                    depuis le mois précédent
                </p>
            </div>

        </div>
        
        {% comment "Optional note" %}
            <!-- <div class="flex flex-wrap gap-4 items-start"> -->
            <div class="dash">
                <!-- <aside class="flex flex-col gap-3 border border-gray-950 rounded-[25px] p-5 lg:w-fit w-full col-span-5 row-span-5 "> -->
                <aside
                    class="flex flex-col gap-3 border border-gray-950 rounded-[25px] p-5  col-span-12 lg:col-span-5 row-span-6 ">
                    <h2 class=" font-medium text-black/80">Factures passées</h2>
                    <div class="flex justify-center  gap-4 md:gap-10 lg:gap-4 w-full h-[25vh] lg:h-full  ">
                        {% for stat_facture in stats_factures %}
                            {% if stat_facture.percent > 0 %}
                                <div class="progressbar  after:h-[{{ stat_facture.percent }}%]"></div>
                            {% endif %}
                        {% endfor %}
                        
                        <!-- <div class="progressbar  after:h-[90%]"></div>
                        <div class="progressbar  after:h-[90%]"></div>
                        <div class="progressbar  after:h-[50%]"></div>
                        <div class="progressbar  after:h-[30%]"></div>
                        <div class="progressbar  after:h-[90%]"></div>
                        <div class="progressbar  after:h-[20%]"></div>
                        <div class="progressbar  after:h-[90%]"></div>
                        <div class="progressbar  after:h-[10%]"></div>
                        <div class="progressbar  after:h-[90%]"></div>
                        <div class="progressbar  after:h-[90%]"></div> -->
                    </div>
                </aside>
                <!-- <aside class=" overflow-hidden px-1 pb-5 lg:-mt-[22vh] flex flex-col gap-3 border border-gray-950 rounded-[25px]  w-full lg:w-[45vw]  "> -->
                    <aside
                    class=" overflow-hidden px-1 pb-5 flex flex-col gap-3 border border-gray-950 rounded-[25px]  col-span-12 lg:col-span-7 " style="grid-row: span 7 / span 7;">
                    <h2 class=" font-medium text-black/80 p-2 ">Programme en cours </h2>
                    <form class="h-[40dvh] overflow-y-auto">
                        {% for last_facture in lastest_factures %}
                            <ul class="flex gap-5 items-center hover:bg-yellow/50 p-3 rounded-2xl overflow-hidden">
                                <li><input type="checkbox" name="" id="" class="checked:bg-yellow"></li>
                                <li class="flex items-center gap-5">
                                    <ul>
                                        <li class="text-[.8rem] text-black/80 inline">{{ last_facture.date_facture|date:'D, d b' }}</li>
                                        <li class="text-lg font-medium -mt-1">{{ last_facture.date_creation|date:'H:i' }}</li>
                                    </ul>
                                    <ul>
                                        <li class="text-lg font-medium ">Facture - {{ last_facture.numero_ordre }}</li>
                                        <li class="-mt-1 text-[.8rem] text-black/80">{{ last_facture.creator.denomination }}</li>
                                    </ul>
                                </li>
                            </ul>
                        {% endfor %}
                    </form>
                </aside>
            </div>
        {% endcomment %}
    </section>

{% endblock %}

src/app/templates/pages/report.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Reporting | Open finances</title>{% endblock %}


{% block content %}

    <!-- Reporting -->
    <section id="REPORTING" class="active">
        <h2 class="mb-8 lg:mb-0 text-xl sm:text-2xl font-medium text-black/80">Reporting</h2>
        <div
            class="slider flex flex-wrap justify-center sm:justify-normal  gap-8 sm:gap-4 w-full h-fit my-3 sm:my-7 ">

            {% for rep in page_obj %}
                <article class="">
                    <div class="flex flex-col gap-4 h-36 mb-4 overflow-hidden  ">
                        <h2 class=" flex justify-between text-base font-semibold  text-black">
                            <span>Rapport n°000123</span>
                            <span>{{ rep.facture.date_facture }}</span>
                        </h2>
                        <p><span>Nombre total de bouteilles de gaz: </span> {{ rep.nombre_bouteilles }}</p>
                        <p><span>Poids total de bouteilles de gaz: </span> {{ rep.poids_bouteilles }}</p>
                        <p><span>Total par catégorie de bouteilles : </span> {{ rep.total_par_categories }}</p>
                    </div>
                    <button class="text-blue-700 font-medium">Modifier</button>
                </article>
            {% endfor %}
            
            <!-- <article class="">
                <div class="flex flex-col gap-4 h-36 mb-4 overflow-hidden  ">
                    <h2 class=" flex justify-between text-base font-semibold  text-black">
                        <span>Rapport n°000123</span>
                        <span>18/01/2024</span>
                    </h2>
                    <p><span>Nombre total de bouteilles de gaz: </span> </p>
                    <p><span>Poids total de bouteilles de gaz: </span> </p>
                    <p><span>Total par catégorie de bouteilles : </span> </p>
                </div>
                <span class="m-auto text-blue-700 text-xl">...</span>
                <button class="text-blue-700 font-medium">Lire tout</button>
            </article> -->

        </div>

        {% include "components/pagination.html" with page_obj=page_obj %}
    </section>

{% endblock %}